[build]
command = "npx prisma generate && next build"
publish = ".next"

[build.environment]
# DATABASE_URL must be set in Netlify site environment variables.
# Tell Next.js / Prisma to skip the client binary check during install
PRISMA_GENERATE_SKIP_AUTOINSTALL = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"
